-- MySQL Script generated by MySQL Workbench
-- Tue Dec 28 14:36:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vehicule_co2_emmission
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vehicule_co2_emmission` ;

-- -----------------------------------------------------
-- Schema vehicule_co2_emmission
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vehicule_co2_emmission` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vehicule_co2_emmission` ;

-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`carrosserie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`carrosserie` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`carrosserie` (
  `ID_Carrosserie` INT NOT NULL,
  `Carrosserie` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`ID_Carrosserie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`energie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`energie` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`energie` (
  `ID_Energie` INT NOT NULL,
  `Carburant` VARCHAR(2) NOT NULL,
  `Hybride` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID_Energie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`gamme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`gamme` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`gamme` (
  `ID_Gamme` INT NOT NULL,
  `Gamme` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ID_Gamme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`marque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`marque` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`marque` (
  `ID_Marque` INT NOT NULL,
  `Marque` VARCHAR(12) NOT NULL,
  `Modele_com` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_Marque`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`voiture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`voiture` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`voiture` (
  `Cnit` VARCHAR(15) NOT NULL,
  `Designation_com` VARCHAR(20) NULL DEFAULT NULL,
  `ID_Gamme` INT NOT NULL,
  `ID_Carrosserie` INT NOT NULL,
  `ID_Energie` INT NOT NULL,
  `ID_Marque` INT NOT NULL,
  PRIMARY KEY (`Cnit`),
  INDEX `Voiture_Gamme_FK` (`ID_Gamme` ASC) VISIBLE,
  INDEX `Voiture_Carrosserie0_FK` (`ID_Carrosserie` ASC) VISIBLE,
  INDEX `Voiture_Energie1_FK` (`ID_Energie` ASC) VISIBLE,
  INDEX `Voiture_Marque2_FK` (`ID_Marque` ASC) VISIBLE,
  CONSTRAINT `Voiture_Carrosserie0_FK`
    FOREIGN KEY (`ID_Carrosserie`)
    REFERENCES `vehicule_co2_emmission`.`carrosserie` (`ID_Carrosserie`),
  CONSTRAINT `Voiture_Energie1_FK`
    FOREIGN KEY (`ID_Energie`)
    REFERENCES `vehicule_co2_emmission`.`energie` (`ID_Energie`),
  CONSTRAINT `Voiture_Gamme_FK`
    FOREIGN KEY (`ID_Gamme`)
    REFERENCES `vehicule_co2_emmission`.`gamme` (`ID_Gamme`),
  CONSTRAINT `Voiture_Marque2_FK`
    FOREIGN KEY (`ID_Marque`)
    REFERENCES `vehicule_co2_emmission`.`marque` (`ID_Marque`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`consommation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`consommation` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`consommation` (
  `ID_Consommation` VARCHAR(15) NOT NULL,
  `Conso_urb` DOUBLE NULL DEFAULT NULL,
  `Conso_exurb` DOUBLE NULL DEFAULT NULL,
  `Conso_mixte` DOUBLE NULL DEFAULT NULL,
  `voiture_Cnit` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Consommation`),
  INDEX `fk_consommation_voiture1_idx` (`voiture_Cnit` ASC) VISIBLE,
  CONSTRAINT `fk_consommation_voiture1`
    FOREIGN KEY (`voiture_Cnit`)
    REFERENCES `vehicule_co2_emmission`.`voiture` (`Cnit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`emmissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`emmissions` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`emmissions` (
  `ID_Emmission` INT NOT NULL,
  `Co2` DOUBLE NULL DEFAULT NULL,
  `CO` DOUBLE NULL DEFAULT NULL,
  `HC` DOUBLE NULL DEFAULT NULL,
  `NOx` DOUBLE NULL DEFAULT NULL,
  `HC_NOX` DOUBLE NULL DEFAULT NULL,
  `Particules` DOUBLE NULL DEFAULT NULL,
  `voiture_Cnit` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Emmission`),
  INDEX `fk_emmissions_voiture1_idx` (`voiture_Cnit` ASC) VISIBLE,
  CONSTRAINT `fk_emmissions_voiture1`
    FOREIGN KEY (`voiture_Cnit`)
    REFERENCES `vehicule_co2_emmission`.`voiture` (`Cnit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vehicule_co2_emmission`.`puissance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicule_co2_emmission`.`puissance` ;

CREATE TABLE IF NOT EXISTS `vehicule_co2_emmission`.`puissance` (
  `ID_Puissance` VARCHAR(15) NOT NULL,
  `Puissance_max` INT NULL DEFAULT NULL,
  `Puissance_admin` INT NULL DEFAULT NULL,
  `Boite_vitesse` VARCHAR(3) NULL DEFAULT NULL,
  `Masse` INT NULL DEFAULT NULL,
  `voiture_Cnit` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Puissance`),
  INDEX `fk_puissance_voiture1_idx` (`voiture_Cnit` ASC) VISIBLE,
  CONSTRAINT `fk_puissance_voiture1`
    FOREIGN KEY (`voiture_Cnit`)
    REFERENCES `vehicule_co2_emmission`.`voiture` (`Cnit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
